'use client';

import React, { useEffect, useState, useCallback } from 'react';
import { ApiClient } from '../lib/api/client';
import { GroqExplanation } from '../lib/api/types';
import styles from './AiExplanationPanel.module.css';

interface AiExplanationPanelProps {
  apiClient: ApiClient;
  signalId: string;
}

export function AiExplanationPanel({ apiClient, signalId }: AiExplanationPanelProps) {
  const [explanation, setExplanation] = useState<GroqExplanation | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [inferenceId, setInferenceId] = useState(`${signalId}-GEN-PENDING`);

  useEffect(() => {
    const updateInferenceId = window.setTimeout(() => {
      setInferenceId(`${signalId}-GEN-${Date.now().toString().slice(-6)}`);
    }, 0);

    return () => window.clearTimeout(updateInferenceId);
  }, [signalId]);

  const fetchExplanation = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const result = await apiClient.requestExplanation(signalId);
      setExplanation(result);
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : 'Inference Engine Unavailable - Retry';
      setError(`Generative inference failed: ${errorMessage}`);
    } finally {
      setIsLoading(false);
    }
  }, [apiClient, signalId]);

  return (
    <div className={styles.panelContainer}>
      <header className={styles.noticeBanner}>
        <span>AI-GENERATED EVIDENCE EXPLANATION</span>
        <span className={styles.badge}>REQUIRES VALIDATION</span>
      </header>

      <div className={styles.contentArea}>
        <h3 className={styles.heading}>Evidence Synthesis & Suggested Investigations</h3>
        
        {isLoading ? (
          <div className={styles.demoLoadingState}>
            <span>Synthesizing evidence...</span>
            <span className={styles.spinnerIcon}>◌</span>
          </div>
        ) : error ? (
          <div className={styles.demoErrorState}>
            <span>Unable to complete analysis</span>
            <button className={styles.retryLinkBtn} onClick={fetchExplanation}>Try again</button>
          </div>
        ) : explanation ? (
          <div className={styles.synthesisContainer}>
            <div className={styles.demoSuccessState}>✓ Analysis complete</div>
            <div className={styles.evidenceBlock}>
              <h4 className={styles.computedBanner}>COMPUTED EVIDENCE</h4>
              <p className={styles.contextText}>Statistical outputs (e.g. PRR, signal thresholds) are sourced deterministically from the backend. They are not generated by AI.</p>
            </div>
            
            <div className={styles.aiBlock}>
              <h4 className={styles.aiBanner}>AI EVIDENCE SYNTHESIS</h4>
              <div className={styles.explanationText}>
                <h5>Why this potential safety signal was flagged</h5>
                <p>{explanation.why_flagged}</p>
                <h5>Evidence summary</h5>
                <p>{explanation.evidence_summary}</p>
                {explanation.limitations.length > 0 && (
                  <>
                    <h5>Limitations</h5>
                    <ul>
                      {explanation.limitations.map((limitation) => (
                        <li key={limitation}>{limitation}</li>
                      ))}
                    </ul>
                  </>
                )}
                {explanation.suggested_questions.length > 0 && (
                  <>
                    <h5>Suggested investigations</h5>
                    <ul>
                      {explanation.suggested_questions.map((question) => (
                        <li key={question}>{question}</li>
                      ))}
                    </ul>
                  </>
                )}
              </div>
            </div>

            <div className={styles.reviewBlock}>
              <h4 className={styles.reviewBanner}>
                {explanation.human_review_required ? 'HUMAN REVIEW REQUIRED' : 'HUMAN REVIEW STATUS'}
              </h4>
              <p className={styles.contextText}>{explanation.disclaimer}</p>
              {explanation.model_used && (
                <p className={styles.contextText}>Model: {explanation.model_used}</p>
              )}
              {explanation.generated_at && (
                <p className={styles.contextText}>Generated: {new Date(explanation.generated_at).toLocaleString()}</p>
              )}
            </div>
          </div>
        ) : (
          <div className={`${styles.explanationText} ${styles.emptyState}`}>
            No explanation generated for this sequence yet. Press &quot;GENERATE EXPLANATION&quot; to review evidence and limitations.
          </div>
        )}
      </div>

      <footer className={styles.footer}>
        <span className={styles.timestamp}>INFERENCE ID: {inferenceId}</span>
        <button 
          className={styles.regenerateBtn} 
          onClick={fetchExplanation}
          disabled={isLoading}
        >
          {isLoading ? 'GENERATING...' : explanation ? 'REGENERATE EXPLANATION' : 'GENERATE EXPLANATION'}
        </button>
      </footer>
    </div>
  );
}
