'use client';

import React, { useState, useEffect, useCallback } from 'react';
import { ApiClient } from '../lib/api/client';
import { ExplanationResponse } from '../lib/api/types';
import styles from './AiExplanationPanel.module.css';

interface AiExplanationPanelProps {
  apiClient: ApiClient;
  signalId: string;
}

export function AiExplanationPanel({ apiClient, signalId }: AiExplanationPanelProps) {
  const [explanation, setExplanation] = useState<ExplanationResponse | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchExplanation = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const result = await apiClient.requestExplanation(signalId);
      setExplanation(result);
    } catch (err: any) {
      const errorMessage = err?.message || 'Inference Engine Unavailable - Retry';
      setError(`Generative inference failed: ${errorMessage}`);
    } finally {
      setIsLoading(false);
    }
  }, [apiClient, signalId]);

  // Removed useEffect to allow explicit strictly-requested empty state initially

  return (
    <div className={styles.panelContainer}>
      <header className={styles.noticeBanner}>
        <span>AI-GENERATED EVIDENCE EXPLANATION</span>
        <span className={styles.badge}>REQUIRES VALIDATION</span>
      </header>

      <div className={styles.contentArea}>
        <h3 className={styles.heading}>Evidence Synthesis & Suggested Investigations</h3>
        
        {isLoading ? (
          <div className={styles.demoLoadingState}>
            <span>Synthesizing evidence...</span>
            <span className={styles.spinnerIcon}>◌</span>
          </div>
        ) : error ? (
          <div className={styles.demoErrorState}>
            <span>Unable to complete analysis</span>
            <button className={styles.retryLinkBtn} onClick={fetchExplanation}>Try again</button>
          </div>
        ) : explanation ? (
          <div className={styles.synthesisContainer}>
            <div className={styles.demoSuccessState}>✓ Analysis complete</div>
            <div className={styles.evidenceBlock}>
              <h4 className={styles.computedBanner}>COMPUTED EVIDENCE</h4>
              <p className={styles.contextText}>Statistical outputs (e.g. PRR, signal thresholds) are sourced deterministically from the backend. They are not generated by AI.</p>
            </div>
            
            <div className={styles.aiBlock}>
              <h4 className={styles.aiBanner}>AI EVIDENCE SYNTHESIS</h4>
              <div className={styles.explanationText}>
                {explanation.explanation}
              </div>
            </div>

            <div className={styles.reviewBlock}>
              <h4 className={styles.reviewBanner}>HUMAN REVIEW REQUIRED</h4>
              <p className={styles.contextText}>This generative interpretation relies on unstructured data and probability mapping. A medical expert must validate these findings.</p>
            </div>
          </div>
        ) : (
          <div className={styles.explanationText} style={{ color: '#71717A', fontStyle: 'italic' }}>
            No explanation generated for this sequence yet. Press "GENERATE EXPLANATION" to review evidence and limitations.
          </div>
        )}
      </div>

      <footer className={styles.footer}>
        <span className={styles.timestamp}>INFERENCE ID: {signalId}-GEN-{new Date().getTime().toString().slice(-6)}</span>
        <button 
          className={styles.regenerateBtn} 
          onClick={fetchExplanation}
          disabled={isLoading}
        >
          {isLoading ? 'GENERATING...' : explanation ? 'REGENERATE EXPLANATION' : 'GENERATE EXPLANATION'}
        </button>
      </footer>
    </div>
  );
}
